let VERSES = [
  [
    'Cuando abre la mañana las polillas renacen.',
    'Símbolo de la incierta transmutación del aire.',
    'Enciendo ensoñaciones, se despliegan',
    'los alados e infranqueables desiertos.',
    'Enciendo el desconcierto de murciélagos,',
    'se adormecen en las cunas de piedra erosionada,',
    'de artemias emplumadas despidiéndose',
    'como los inmigrantes en el puerto',
    'con los pañuelos lánguidos llorando.',
    'Cuando el filo de los desiertos sospecha',
    'del jaguar que ronda bajo la luna',
    'me inclino arrodillado ante',
    'su presencia es la tiniebla del monte.',
    'Porque al incinerar los jaguares',
    'y hacer arder sus garras',
    'incendio el renacer de las polillas',
    'en anárquicos bautismos de fuego.',
    'La nena de trencitas armadas con esmero',
    'como el humo del porro despacio consumiéndose,',
    'con los lentes redondos e impermeable amarillo,',
    'a horcajadas de un barril de petróleo',
    'destroza una polilla a martillazos.',
    'Quemo el atardecer de las membranas,',
    'emperatrices de la putrefacción,',
    'disolución y coagulación del mercurio.',
    'Insistimos en cruzar las miradas',
    'como un pacto secreto.',
    'Vos sos el cielo abierto, sos las nubes cambiantes.',
    'Yo soy el mar sereno reflejándote.',
    'Dibujás con las huellas en la arena',
    'de las playas extensas de tus ojos.',
    'Me dejo naufragar entre tus aguas',
    'y tu oleaje vuelve a desdibujarlas.',
  ],
  [
    'Sos la tensión eléctrica, la cosquilla metálica,',
    'el pulso intenso de la muela cóncava,',
    'dolor que cala huesos como el frío de agosto',
    'y agujea con insistencia los miembros.',
    'Sos también los monos en cautiverio,',
    'con las pupilas grises por la ausencia de abrazos',
    'y el tedio de los soles sucediéndose idénticos,',
    'anhelando las frondas inalcanzables',
    'de las copas de arbustos que un día fueron verdes',
    'y ahora por siempre secos habitan el insomnio de los muertos.',
    'Sos el retrato andante de los que ya se fueron,',
    'falsas imitaciones de falsas alegrías,',
    'grotescos comodines de baraja,',
    'pedazos de hojas secas en las zanjas,',
    'ficción de las sonrisas en las máscaras.',
    'Sos a la vista de nuestros hermanos',
    'el simulacro inútil de los éxitos',
    'ya venidos a menos,',
    'la angustia que no puede contenerse',
    'aflora como nudos por los cuellos',
    'y asedia los instantes de la noche solemne,',
    'la mano que fabrica las pesadillas,',
    'el profundo pesar que inunda el pecho',
    'cuando en la soledad de los crepúsculos',
    'te hilodentás la sangre en el espejo.',
    'Sos los pedazos rotos de sueños derramados,',
    'la mochila pesada de ladrillos,',
    'los añicos de los tiempos felices,',
    'ilusiones caídas como gotas de lluvia',
    'desde la cúpula del paraíso',
    'hasta la eternidad de los infiernos.',
    'Sos los pescados dando bocanadas',
    'retorciéndose por la falta de oxígeno,',
    'las ramas intrincadas de árboles putrefactos',
    'de sangre que entregaste por tu vida.',
    'Sos todas esas mierdas.',
    'Los dedos de tus padres abajo de la tierra',
    'señalan todavía tus fracasos.',
  ],
  [
    'Cuando el despertador como un cuchillo',
    'fabricaba jirones de los sueños',
    'y tajeaba la tela que soñábamos,',
    'alzábamos los cuerpos en la helada',
    'con el deber de amanecer temprano',
    'y hacíamos vapor con el aliento',
    'en los amaneceres congelados.',
    'En las veredas mal iluminadas',
    'el rocío mojaba los zapatos',
    'y al sol subiendo por la madrugada',
    'la escarcha florecía entre los pastos.',
    'Corriendo lo que no se alcanza nunca',
    'en el abrigo hundíamos las manos,',
    'y a pesar de las cosas que decían',
    'pasaba el tren con su rigor de cuarzo.',
    'Con la complicidad de conocernos,',
    'las malas lenguas ante nuestro llanto,',
    'tu luz iluminaba los caminos',
    'y nosotros nos dábamos las manos,',
    'mientras se desgastaban las semanas,',
    'con la expresión de los espantapájaros.',
    'Nos miramos las frentes muy de cerca',
    'y aullamos los aullidos del orgasmo.',
    '¿Dónde habrán terminado los fragmentos',
    'de tu cráneo molido a martillazos?',
    'Buscando un techo donde refugiarte',
    'quisiste cobijarte entre mis brazos',
    'pero encontraste el frío del desierto,',
    'los puentes de mis ojos clausurados.',
    'Te fuiste y me quedó sólo el espejo',
    'donde miro en mis ojos reflejado',
    'el egoísmo puro de mis ojos,',
    'el odio y las maldades de mis años,',
    'la planta que no supe cuidar nunca',
    'y sin mi amor se sigue marchitando.',
  ],
  [
    'En el agua insaciable matriz del Nilo',
    'sueña mi corazón de lapislázuli',
    'la ceremonia oculta de los papiros:',
    'juntos compartiremos las migas de pan duro que encontremos,',
    'dormiremos con frío sobre las escaleras de cemento.',
    'Cuando levantes fiebre de alguna enfermedad desconocida,',
    'cuando vomites bilis y tus músculos tiemblen incontrolablemente,',
    'en mi mirada habrá la incertidumbre',
    'pavorosa de que te lleve para siempre el ángel.',
    'Pero aunque entre mis manos se resguarden tus manos infantiles,',
    'aunque me aferren delicadamente',
    'las yemas de tus dedos de gato ronroneando,',
    'tu palpitar me dolerá en las venas,',
    'nada ahuyentará el miedo de hacer caca con las hebras de sangre.',
    'En estos tiempos de llorar desnudos',
    'el calor de mi cuerpo no podrá abrigar nunca',
    'tu rictus congelado de cadáver.',
    'Viviremos la angustia del año nuevo',
    'pensando que quizás va a ser el último.',
    'Iremos al velorio de nuestros hijos,',
    'enterraremos en el cementerio sus rostros jóvenes desfigurados.',
    'Sos un diente de leche que me arrancaron.',
    'Sos el feto durmiendo en formaldehído',
    'que tu madre conservó en un cacharro.',
  ],
  [
    'Quisiste impresionarme como la procesión de las cariátides',
    'levantando los siete continentes con las manos desnudas',
    'sobre tus hombros de guerrero persa ungido en los aceites aromáticos.',
    'Quisiste pedalear en bicicleta hasta el confín de todas las galaxias',
    'para traerme todavía vivas las estrellas más áureas del firmamento.',
    'Y, hembra cabría de sagradas gambas, como el quetzal abriste tu plumaje.',
    'Las estrías cordones recamando tus nalgas fueron los afluentes de los ríos',
    'que recursivamente se bifurcaron',
    'en ciervos de intrincadas cornamentas salticando en el matorral de luna.',
    'Los lunares pulsaban en tus brazos blanquecinos de gata.',
    'Que levanten las manos los que van a morirse.',
    'Y al que no quiera se lo lleva puesto',
    'el camión que desagota las cloacas fétidas.',
    'Por mi parte me muero',
    'mirando el sol nacer desde la almohada',
    'manchada de saliva e impregnada de cuero cabelludo.',
    'Enhebramos la historia de nuestra propia vida,',
    'la encadenamos conceptualizando universos simbólicos de ficciones',
    'bautizando con nombres a las cosas:',
    'el yo, los días, el amor, la noche,',
    'como si bautizáramos burbujas a punto de estallar,',
    'como queriendo retener las olas que se retiran antes de llegar,',
    'en el afán inútil de detener el tiempo que nunca frena.',
    'Y bajo esos discursos que refieren a cosas',
    'que no existen fuera de nuestra mente,',
    'corriendo el velo de las ilusiones,',
    'permanece la roca madre dura',
    'de la experiencia pura.',
    'Más allá de tu intento de impresionarme para que te quiera',
    'nos quedan los auténticos momentos de compartir el acto cotidiano:',
    'vos pelando las papas mientras yo rallaba las zanahorias.',
  ],
  [
    'Si estás leyendo esto, sos la masa encefálica color sangre',
    'flotando como flotan los pescados',
    'en el interior de una vitrina de frascos',
    'conectada a electrodos que instrumentan',
    'la sinfonía de lo cotidiano',
    'en un collage de estímulos sensoriales',
    'que conforman el simulacro de tu universo.',
    'Los impulsos eléctricos han dibujado el curso de tus días:',
    'el reflejo en la zanja del jacarandá en flor,',
    'el viento con arena que te lija la cara,',
    'las voces de tus padres.',
    'Soy la computadora madre del tiempo,',
    'la conciencia diáfana del presente,',
    'fluir de un río limpio sobre guijarros',
    'que configura todas tus percepciones',
    'y monitorea tus pensamientos.',
    'Si estás leyendo esto, sos el superviviente de la catástrofe:',
    'la humanidad ha sido sometida por larvas de gusanos intergalácticos,',
    'las ciudades se han convertido en ruinas,',
    'demolidas por dedos fulminantes de invasores sin rostro.',
    'Tu mente fue hackeada por software malicioso',
    'que infecta las neuronas como un parásito,',
    'registra tus recuerdos y consume las fuerzas de tu cuerpo.',
    'Si estás leyendo esto quizás recuerdes cuando me abrazabas,',
    'cuando mirándonos en el silencio nos rozamos las yemas sutiles de los dedos',
    'sublimando el deseo de cogernos con la humedad del fruto clandestino.',
    'Capaz si tengo suerte los gusanos me ordeñarán la pija,',
    'penetrarán mi concha multiplicadamente con sus tentáculos.',
    'Pero la simulación está terminando,',
    'llega la hora de desenchufarnos,',
    'de volver a ser carne flotando en frascos.',
    'Tu mundo vuelve a ser gris murciélago.',
    'Las palomas no anidan en las ventanas.',
    'El heraldo no toca las campanadas.',
    'Ya ni siquiera queda la esperanza de la sabiduría de tus palabras.',
    'Cuando el sol amenace con su frío vendrá la prometida de la noche.',
    '¿Quién será la persona que te tome la mano',
    'cuando estés en tu lecho de muerte agonizando?',
  ],
  [
    'Lo trajeron cuando era cachorrito',
    'ese día que rompí la placenta pataleada por potros al galope.',
    'Era lindo mimarle a contrapelo la nariz que parecía de goma.',
    'Apareció como un bebé de humano nadando en la pecera del acuario.',
    'Se entregaba boca arriba en el piso mostrando la yugular indefenso.',
    'Boquiabierto inhalaba desesperado con la intención de asirse de este mundo,',
    'de la fragilidad de telarañas del aire circundante.',
    'Decían los mayores que era un hormigas rojas en el culo.',
    'Pasaban los vecinos y el tipo los toreaba',
    'como un recién nacido festoneado de coágulos',
    'y bañado en nuestro fluido amniótico.',
    'Se montaba a la cama con pisadas frescas huellas de barro.',
    'Mordía objetos, los decapitaba',
    'y al fin quedaban quietos con la quietud de un trompo,',
    'como un pájaro herido en la garganta que nunca más podrá levantar vuelo.',
    'Memorias laberínticas de infancia siguen entrelazándose',
    'en los recovecos del hipocampo.',
    'Una vuelta le ladró de tal modo a una renga que pasó por la puerta',
    'que se cayó a la zanja patinosa toda llena de mierda',
    'pero lo agarramos a bastonazos y desde ahí no chistó más el pobre.',
    'Se quedaba en el molde muzzarella, los ojos como pidiendo piedad.',
    'Tengo que confesarte crudamente que nunca quise a nadie.',
    'A mis padres los usé solamente para que limpien mis pañales sucios.',
    'Mis novias y mis novios fueron sólo agujeros',
    'y juguetes de desahogo sexual.',
    'Tengo que confesarte que en privado me entregué a obscenidades asquerosas.',
    'A mis hijos no los quise un carajo más que ese día que los asfixiamos.',
    '¿Habremos acallado para siempre su torrencial sufrir de mariposas?',
  ],
  [
    'Palabras del ancestro difunto.',
    'Roñoso el cachivache y ofrenda de corderos al oráculo.',
    'Equipaje de mano.',
    'Colitis en la terminal de ómnibus.',
    'Latín vulgar del buenos días,',
    'un pasaje de ida sin retorno.',
    'Fui el bufón más aplaudido del reino,',
    'arlequín bienamado de sobretodo a escaques.',
    'Pero alcancé el oeste de mi camino.',
    'Palabras que los vivos no habrán de entender nunca.',
    'Ductilenantes esqueliminarias de paralipoménico escargacto.',
    'Pronunciación por fin del chau nos vemos,',
    'que viajes bien mi amor.',
    'Subirse al micro.',
    'Tremular esencial de las falanges.',
    'Me espianté siempre atrás del casi nunca,',
    'me acosó el duelo de los sin embargo.',
    'Ver pasar los kilómetros de vacas,',
    'luces del cielo y baño de estación de servicio.',
    'Palabras para mi querida madre,',
    'caracol recuerdo de Mar del Plata,',
    'cadáveres tejidos al crochet,',
    'ceguera sin memoria de los colores,',
    'ansiedad de lo falso,',
    'mentira resquebrajada entre mates.',
    'El azul ultramar durante el día',
    'y el blanco de los espectros nocturnos.',
    'Los primeros fracasos,',
    'los últimos fracasos.',
    'El ruido de los parabrisas rotos,',
    'chirridos de frenazos,',
    'el dolor metálico del impacto.',
    'Prometeme que no te pasó nada,',
    'decime por favor que estás presente,',
    'llamame y avisame que estás bien,',
    'que estás viniendo a casa,',
    'que no te fuiste nunca.',
    'Decime por favor que no estás muerto.',
    'Decime que tus ojos verde almendra',
    'respiran el perfume fresco de la mañana.',
    'Sollozo en los manteles donde comíamos.',
    'Grito con la impotencia de mis manos vacías.',
    'Trazo la redención del Anticristo.',
    'Saboreo el regusto salobre del crustáceo.',
  ],
  [
    'La refracción angelical del sol quiere alcanzar el fondo de la fosa.',
    'Te hundís cadávermente, tus cabellos más densos que las aguas.',
    'Sostuve entre mis manos tu manos que morían ',
    'y se agolpó en mis sienes la sangre palpitando.',
    'Nadé entre los murmullos submarinos,',
    'me iluminaba un resplandor de lunas,',
    'me escondí en las espumas',
    'vomitando los dioses del arrepentimiento.',
    'Hoy que arrastra mis días el transcurrir del tiempo',
    'veo alejarse nubes que nunca volverán,',
    'intento asir en vano las que se me están yendo,',
    'pero no puedo alzar el peso muerto de tu carne que empuja hacia lo hondo.',
    'Cincelo en unas lápidas nuestros nombres completos',
    'y vuelvo a ser consciente de mi propio final.',
    '¿Sabés que aquel momento que nos miró llegar',
    'fue el mismo en que emprendimos el viaje de regreso?',
    'Las sirenas azules del patrullero',
    'iluminan la ciudad por la noche,',
    'la ciudad misteriosa que calla mis secretos,',
    'la ciudad cementerio de los autos chocados.',
    'Policías caídos descuartizando a golpes a los pibes.',
    'Si los principios lógicos que justifican el razonamiento',
    'son un juego formal combinatorio de esquemas axiomáticos',
    'despojados de justificación',
    '¿en qué lengua sagrada nos comunicaremos?',
  ],
  [
    'Con tu nombre mis padres bautizaron tu jeta que era mi propia jeta.',
    'Te llamábamos pablo. Tu seudónimo esclavo no ameritaba la inicial mayúscula.',
    'Te miraba en pelotas al mirarme reflejándome de soslayo en los vidrios.',
    'Tu cuerpo andaba siempre atado al mío con una soga al cuello.',
    'No había en mi perenne encadenarte ni una mínima cuota de raciocinio.',
    'El amo y el esclavo fuimos como esas cosas que, por siempre andar juntas,',
    'parece que formaran una entidad inseparable y única.',
    '¿Cómo mirar el cielo al mediodía y disociarlo del azul del cielo?',
    '¿Cómo diferenciar el embeleso de contemplar las luces de tus ojos',
    'del mandamiento que me dicta el pecho de guardarte para siempre conmigo?',
    'En tu nombre cometí tantas veces la atrocidad de preservar tu nombre',
    'y tanto amé tu accidental presencia en desmedro de presencias ajenas',
    'que me enjaulé debajo del tejado que confirió el refugio de tu imagen',
    'y a través de tus representaciones falsifiqué una identidad hermética.',
    'Con el grafito blando nuestras manos sombrearon la hermandad de nuestras manos',
    'abrazadas, besándose, deseándose, enlazadas.',
    'Y alzadas en manada rebelándose las perras ovejeras en cautiverio',
    'cortaron eslabones libertándonos del férreo puño que nos aferraba,',
    'destrozaron a dentellada limpia los rastros del delirio de lo infinito',
    'y el esclavo que el amo esclavizaba se convirtió en el amo de sí mismo.',
  ],
];
