
let VERSES = [
  [
    "La vieja corva y con la voz quebrándose",
    "manifestó que otrora,",
    "cuando no había espejos, sus hermanos",
    "se solían reflejar en el agua.",
    "",
    "Caminamos al lago mirando este silencio.",
    "La brisa meció, apenas, el agua como pétalos.",
    "Me dio las manos ásperas de años",
    "y sentí que eran ramas de algún árbol.",
    "",
    "El lago reflejó los rostros anchos.",
    "Nos colmaba esa alegría sencilla",
    "del destello del sol.",
    "",
    "La mujer vieja se murió en la orilla,",
    "solté sus manos todavía tibias",
    "y del cuerpo que volvía a ser nada",
    "brotó el reflejo de la propia vida."
  ],
  [
    "Vuelvo a caballo al pueblo donde aprendí mi nombre.",
    "En la casa de azulejos islámicos",
    "mis padres ya no viven.",
    "",
    "De la vid cuelgan ubres",
    "ácidas en racimo",
    "a la espera de alguno que las coseche.",
    "",
    "Abro los desvencijados roperos.",
    "Sopeso con los dedos entreabiertos",
    "los eslabones, gráciles",
    "simulacros de plata,",
    "la incrustación sutil del vidrio",
    "que imita torpemente la esmeralda.",
    "",
    "El cielo de golpe se puso negro.",
    "Nunca vi tanta lluvia y tanto viento.",
    "",
    "Abrazando el calor de las frazadas",
    "que fueron de mis viejos",
    "los recuerdos vuelven como relámpagos",
    "y en la quietud del dormitorio",
    "oigo el gorjeo de los pájaros."
  ],
  [
    "Concilio de los brujos y las brujas",
    "descifrando los tratados de alquimia.",
    "",
    "Invocando presencias ancestrales",
    "trazan con las cenizas de un humano",
    "un pentagrama arcano que refulge.",
    "",
    "Al balbucear en una lengua muerta,",
    "el aire va poblándose de sílabas",
    "que hibernaron milenios",
    "esperando el día que las pronuncien.",
    "",
    "Bajo el temblor del suelo,",
    "desperezándose de su letargo,",
    "los demonios conjurados del Éufrates",
    "cuyos dientes las cabezas cercenan",
    "abren al fin sus alas sepulcrales",
    "y ascienden a otros planos de conciencia.",
    "",
    "Lo que he visto no puedo describirlo:",
    "los dibujos de los esquizofrénicos,",
    "tortura de geometrías concéntricas,",
    "avatares que el profeta predijo.",
    "",
    "Me encomiendo a los númenes sumerios,",
    "rezo mis últimas plegarias.",
    "Y mi cordura, al fin, al ver mi torso",
    "sacrificado en el altar de cuarzo",
    "me abandona en medio de tus palacios."
  ],
  [
    "Enamorarse es atender al tenue",
    "detalle verde agua",
    "bordado en punto ojal de tu camisa:",
    "susurro imperceptible del verano",
    "que acuna a la nacida flor del cardo.",
    "",
    "Es albergar secretamente",
    "el anhelo irreal",
    "de encontrarnos por azar en los márgenes,",
    "de una visita inverosímil tuya",
    "con tu laúd en mi balcón abierto.",
    "",
    "Es la embriaguez serena",
    "que entibia los abdómenes",
    "y sube al corazón cuando sabemos",
    "que nos gustamos.",
    "",
    "Es la impaciencia intolerable",
    "al computar las horas",
    "que nos quedan hasta el próximo beso.",
    "",
    "Amar, en cambio,",
    "es el pausado riego de la planta,",
    "humedecer la tierra negra",
    "durante lentas décadas.",
    "",
    "Es la germinación de los retoños",
    "que serán árboles",
    "que darán frutos con semillas vírgenes.",
    "",
    "Es la labor de la cartografía",
    "minuciosa de los atardeceres,",
    "de nuestros accidentes orográficos:",
    "las caras imperfectas tuya y mía.",
    "",
    "Son tus ojos que evocan al mirarme",
    "las palabras que no son las palabras,",
    "la costumbre de tomarnos las manos",
    "en las veredas.",
    "",
    "Es la certeza",
    "del faro firme que en el horizonte",
    "alumbra el mar con tu inmortal presencia."
  ],
  [
    "Remando el delta con olor a barro,",
    "el sol retrata su vitral cubista,",
    "los retazos de luces color ámbar",
    "a través de los tallos de los ceibos.",
    "",
    "Vemos entonces la espesura abriéndose,",
    "el cielo azul traslúcido del claro.",
    "A los lejos cargan bolsos señoras",
    "con dos rostros que no conoceremos.",
    "",
    "Me remolcan hasta la pieza sola",
    "que crece entre los líquenes:",
    "galpón hecho un quilombo",
    "de juguetes en ruinas,",
    "el olor acre del jabón en polvo,",
    "la ropa sucia, palas oxidadas",
    "y baldes sin pintura que se secó.",
    "",
    "Me acuestan en el piso polvoriento",
    "y ante el grito de que traigan ayuda",
    "viene corriendo un hombre grande en cuero",
    "todavía mate enlosado en mano.",
    "",
    "Comí un yuyo guaraní venenoso",
    "y entré a sudar como el caballo enfermo.",
    "Pulso eléctrico que recorre los nervios,",
    "me derrumban el vértigo y las náuseas.",
    "No escucho más las voces apagadas.",
    "",
    "Entiendo sin embargo por cómo están mirándome",
    "que ya estoy muerta."
  ],
  [
    "Me niego a resignarme a lo posible",
    "y a hacer revoluciones por lo bajo.",
    "Me niego a pesadillas a destajo",
    "a cambio de modorras apacibles.",
    "",
    "Me niego a las mandíbulas terribles:",
    "al aguijón del áureo escarabajo",
    "que a mi pecho mascada mierda trajo",
    "y me inyectó un dolor indestructible.",
    "",
    "Me niego a sepultar en el olvido",
    "las palabras que un día me dijiste",
    "cuando dejando el ya desierto nido",
    "",
    "tus alas blancas de gaviota abriste",
    "y, aleteando, su nítido sonido",
    "me dejó en el lugar del que te fuiste."
  ],
  [
    "¿Qué soy más que la carne del presente que pasa,",
    "cristal de la conciencia pulida que fluyendo",
    "experimenta el devenir que nace?",
    "",
    "La experiencia del cuerpo se disuelve",
    "en colores puros que se entrecruzan.",
    "La fusión de crayones",
    "y el irisado tornasol del nácar",
    "son náusea, angustia, lágrimas,",
    "alivio, carcajadas,",
    "mil diminutas flores de lavanda.",
    "",
    "Ya no soy esa nena secuestrada en el monte:",
    "con las manos filosas rebané sus testículos",
    "y los dejé tirados en un palo borracho.",
    "",
    "Soy todos y cada uno de los momentos:",
    "los elefantes del zoológico,",
    "las medusas chasqueando en el océano,",
    "mi nombre es las estrellas del firmamento.",
    "",
    "Soy la madre que parió el universo,",
    "el augurio ominoso del benteveo,",
    "los ojos que mirándose a sí mismos",
    "se desfiguran y se configuran."
  ],
  [
    "Soñé que a luz de vela charlando en occitano",
    "iluminaba un pergamino",
    "en oro y goma arábiga",
    "con cálices sangrales, basiliscos ignívomos",
    "y las pijas erectas de los faunos",
    "con alas de murciélago.",
    "",
    "Me despierto en un tren a los suburbios",
    "entre la sarna de los perros,",
    "un viejo mutilado pregonando gaseosas",
    "y pintura rupestre fálica en los asientos.",
    "",
    "No se mira directamente al sol:",
    "soslayo el resplandor incandescente",
    "de los seres humanos de la calle",
    "que por sernos inútiles",
    "mandamos a dormir sobre el cemento,",
    "a tener por almohada la intemperie,",
    "a limosnear por la supervivencia,",
    "a atesorar desperdicios ajenos.",
    "",
    "Llego a los pagos de mi vieja",
    "donde los equinoccios se preceden",
    "tomando el mate de la tardecita,",
    "tendiendo ropa al sol",
    "con su jeta de calendario maya",
    "solemne ante el sacrificio infantil.",
    "",
    "Le hago mimos al gato que le llora",
    "el ojo mocho.",
    "Permanece en el mármol de la mesada",
    "ajeno al tiempo.",
    "",
    "Miro las fotos de mi hermana",
    "cuando le faltaban dos incisivos,",
    "de las fiestas cuando mi viejo estaba.",
    "",
    "Sé que un día esta casa va a quedar sola.",
    "",
    "Me despido otra vez de mi mamá,",
    "sin sospechar que esta vez es la última, ",
    "y me tomo el colectivo de vuelta."
  ],
  [
    "Tambores funerarios polirrítmicos",
    "rezongan en lenguas de los bantúes.",
    "Me amortajan",
    "en el precioso lino",
    "recamado",
    "del plumaje vistoso",
    "de pájaros turquesa.",
    "",
    "Los ancestros",
    "rondan entre los vivos",
    "con máscaras grotescas del rito fúnebre.",
    "Me abandono a los compases frenéticos,",
    "a la convulsión del trance mortuorio.",
    "",
    "Mi nombre es un amuleto simbólico:",
    "palabra mágica que da la vida,",
    "palabra mágica que la arrebata.",
    "",
    "A cambio de dos óbolos",
    "en las órbitas huecas de los ojos",
    "el barquero me cruza desde el sueño",
    "a la vigilia de los que no sueñan.",
    "",
    "Transito las acequias empedradas",
    "al parque celestial del más allá.",
    "",
    "Conmigo morirán las memorias",
    "de las ingles ungidas",
    "en el olor rancio del sexo,",
    "de tu boca posándose sobre mi mano abierta,",
    "de la sangre rodando por los muslos desnudos",
    "tiñendo de nervaduras la tierra."
  ],
  [
    "A la vera del río",
    "crecen las campanillas,",
    "los transeúntes andan",
    "sin mirar las espigas,",
    "florecen en noviembre",
    "los árboles de lilas",
    "y de la madreselva",
    "los zarcillos se rizan.",
    "",
    "A tus dieciséis años,",
    "mariposa de noche,",
    "te carcomió la enfermedad,",
    "vino a buscarte el monigote",
    "para sumirte en las profundidades.",
    "",
    "Quise darte mi corazón entero",
    "y no pude arrancármelo del pecho.",
    "",
    "Cuando los eones pasen",
    "y la Tierra se seque",
    "y se extingan los rastros de nuestros cuerpos",
    "y se borren todos estos momentos",
    "¿quiénes seremos?",
    "¿cómo habremos de volver a encontrarnos?"
  ]
];

