
let VERSES = {
  '0': [
    new Verse('el hombre fue a la Luna y — dejó a la esposa en casa (que)'),
    new Verse('se quedó a lavar sábanas y a cuidar a los hijos (porque)'),
    new Verse('ella también de niña quiso ser astronauta (para)'),
    new Verse('explorar otros mundos y sus eras geológicas (pero)'),
    new Verse('cadenas invisibles la anclaron a la tierra (porque)'),
    new Verse('sus padres le ordenaron, quizá benevolentes (que)'),
    new Verse('de aquel árbol prohibido no deberás comer (:)'),
    new Verse('las nenas no se meten en cosas de varones, (que)'),
    new Verse('deben poner la mesa, zurcir los calzoncillos, (que)'),
    new Verse('deben priorizar siempre servir a su marido (que)'),
    new Verse('será un hombre derecho, gentil y caballero (que)'),
    new Verse('podrá con su hipertrofia cuidar del sexo débil (y)'),
    new Verse('enderezarla a golpes cuando le corresponda (porque)'),
    new Verse('el mundo hostil no es sitio para una vulva sola (sin)'),
    new Verse('un falo que complete la pieza que le falta, (que)'),
    new Verse('ponga semillas para fertilizar el vientre (que)'),
    new Verse('no es más que una maceta donde afloran bebés (que)'),
    new Verse('ha de nutrir la madre con su vida y su sangre (para_que)'),
    new Verse('del bebé crezca un hombre sin rasgos femeninos (que)'),
    new Verse('quizás viaje a la Luna como viajó su padre (porque)'),
  ],
  '1': [
    new Verse('cuentan por ahí: (que)'),
    new Verse('tu madre (que)'),
    new Verse('escapó de la ciudad (donde)'),
    new Verse('tenía que lavar los inodoros (que)'),
    new Verse('cagaban los adinerados para (que)'),
    new Verse('no la fajara tu padre (que)'),
    new Verse('la reventó a golpes un día (pero)'),
    new Verse('no terminó en la cárcel (porque)'),
    new Verse('era amigo del diputado (que)'),
    new Verse('regenteaba prostitutas (que)'),
    new Verse('eran menores de edad y (que)'),
    new Verse('fueron secuestradas por policías (que)'),
    new Verse('tenían hijas en el jardín de infantes (donde)'),
    new Verse('las nenas no podían jugar al fútbol (porque)'),
    new Verse('tenían que jugar a la mamá (para_que)'),
    new Verse('un cura pedófilo avale algún día (la)'),
    new Verse('santa unión del matrimonio en el (que)'),
    new Verse('un vestido blanco atestiguará la integridad (de)'),
    new Verse('su himen inmaculado, no sea cosa (que)'),
    new Verse('las malas lenguas divulguen lo (que)'),
  ],
  '2': [
    new Verse('tenés que mantenerte — callada, vos no hablés (porque)'),
    new Verse('sos una mina y nunca tendrás ni voz ni voto (porque)'),
    new Verse('no vas a entender nunca cómo funciona el mundo (que)'),
    new Verse('gobiernan los señores de sacos y corbatas (mientras)'),
    new Verse('la ciudad sin embargo sigue andando (por)'),
    new Verse('el trabajo invisible de miles de nosotras (cuyo)'),
    new Verse('mandato es fregar pisos, amamantar bebés, (a_lo_sumo)'),
    new Verse('tener las tetas grandes y la cintura chica (y_que)'),
    new Verse('nuestros cuerpos se ajusten al canon de belleza (que)'),
    new Verse('postulan en los medios de comunicación (que)'),
    new Verse('generando riqueza para los poderosos (mientras)'),
    new Verse('hay miles de nosotras que sufren anorexia (por)'),
    new Verse('vernos la celulitis en las piernas (que)'),
    new Verse('no fueron retocadas por medios digitales, (por)'),
    new Verse('los pieses magullados por los tacos (con)'),
    new Verse('las trenzas maltratadas por cosméticos (que)'),
    new Verse('venden publicidades anticuadas (que)'),
    new Verse('interrumpen la discusión eterna (sobre)'),
    new Verse('el futuro de nuestra economía (donde)'),
    new Verse('opina solamente el hombre blanco (porque)'),
  ],
  '3': [
    new Verse('esa vez que te dijeron (qué)'),
    new Verse('culo mamá en la calle en (que)'),
    new Verse('volvías de la escuela (donde)'),
    new Verse('tu profesor hacía comentarios (con)'),
    new Verse('los varones sobre los cuerpos (de)'),
    new Verse('tus compañeras y pensábamos (que)'),
    new Verse('eso era lo natural y (que)'),
    new Verse('era culpa nuestra (por)'),
    new Verse('haber nacido mujeres (que)'),
    new Verse('tenemos que usar pollera para (que)'),
    new Verse('puedan medir nuestra fertilidad (en)'),
    new Verse('el ancho de nuestras caderas (siempre)'),
    new Verse('divinas como exigen las revistas y (sin)'),
    new Verse('olor a sangre podrida del período (que)'),
    new Verse('cada luna te desgarra el vientre (pero)'),
    new Verse('vos tenés (que)'),
    new Verse('hacer como si nada pasara y poner cara (de)'),
    new Verse('princesa (porque)'),
    new Verse('si no sos una yegua malcogida (que)'),
    new Verse('pone cara de orto (como)'),
  ],
  '4': [
    new Verse('dicen que soy muy poco — femenina y también (que)'),
    new Verse('soy medio desprolija para ser una nena, (que)'),
    new Verse('tengo las manos gordas y las caderas grandes, (que)'),
    new Verse('tengo las piernas flacas como los opiliones, (que)'),
    new Verse('por qué a la edad que tengo nunca tuve pareja, (que)'),
    new Verse('por qué estoy en pareja si este no me conviene, (que)'),
    new Verse('cuándo voy a casarme, que ya es hora, (que)'),
    new Verse('hay que ser obediente, planchar y cocinar, (que)'),
    new Verse('ya comí demasiado para ser una chica, (que)'),
    new Verse('salir así vestida parecés una puta, (que)'),
    new Verse('tengo que ir bien peinada, (que)'),
    new Verse('me queda mal el pelo así de corto, (que)'),
    new Verse('se me ven las raíces y tengo que teñirme, (que)'),
    new Verse('no tengo que andar tanto con varones, (que)'),
    new Verse('no tengo que decir malas palabras, (que)'),
    new Verse('esas no son maneras de hablar de señorita, (que)'),
    new Verse('si sigo en este rumbo me voy a quedar sola, (que)'),
    new Verse('tengo que conseguirme un macho que me empreñe, (que)'),
    new Verse('tengo que tener hijos antes de los cuarenta (que)'),
    new Verse('la chupen (quienes)'),
  ],
  '5': [
    new Verse('tu lugar es en la cocina, tenés (que)'),
    new Verse('esperar al señor y servirlo bien (en)'),
    new Verse('la cama y procrear pero (no)'),
    new Verse('sos una ciudadana con derecho al sufragio (porque)'),
    new Verse('sos a lo sumo un animal (como)'),
    new Verse('ya han dicho los grandes pensadores (de)'),
    new Verse('todas las civilizaciones a la mujer hay (que)'),
    new Verse('atarla como a la mula para (que)'),
    new Verse('no se escape y (si)'),
    new Verse('se llega a retobar usar el látigo, (que)'),
    new Verse('es pérfida (como)'),
    new Verse('la serpiente y hay (que)'),
    new Verse('guardarla bien, ponerle (el)'),
    new Verse('anillo en el dedo y el cepo en el tobillo (como)'),
    new Verse('al ave enjaulada y (el)'),
    new Verse('cinturón de castidad (porque)'),
    new Verse('si no a esa máquina de fabricar bebés la (puede)'),
    new Verse('usar el primero (que)'),
    new Verse('la agarre, por eso siempre ha (de)'),
    new Verse('guardarse bajo llave, (porque)'),
  ],
  '6': [
    new Verse('gotas de sangre y óxido — rodaban por mis muslos (que)'),
    new Verse('aprieto fuertemente como me han enseñado (para_que)'),
    new Verse('mi sexo sea un secreto invulnerable y santo (que)'),
    new Verse('sólo puede decirse con la voz por lo bajo (a_pesar_de_que)'),
    new Verse('una vez de mis labios fue tuya la ambrosía (y_nos)'),
    new Verse('amamos como efímeras, y cuando te veía (cada)'),
    new Verse('una con su marido como Dios lo legisla (en)'),
    new Verse('nuestros ojos ardía todavía aquel brillo (que)'),
    new Verse('los padres reprobaron inapeblablemente (porque)'),
    new Verse('los vientres-bombos han de cumplir su cometido (:)'),
    new Verse('dar a luz nuevos cuerpos, perpetuar nuestra especie (con)'),
    new Verse('los pechos, nacarados manantiales de leche (que)'),
    new Verse('objetos de deseo de la silueta en sombras (que)'),
    new Verse('te persigue las huellas, te espera en cada puerta (para)'),
    new Verse('atarte, amordazarte en el baúl de un auto (donde)'),
    new Verse('nadie habrá de escuchar tus alaridos secos (de)'),
    new Verse('socorro y quizá entonces aprendas que en la vida (es)'),
    new Verse('menester defenderse con tarascones y uñas (porque)'),
    new Verse('nadie vendrá en tu auxilio cuando te encuentres sola (como)'),
    new Verse('nadie vino a acudirme cuando lloré en silencio (que)'),
  ],
  '7': [
    new Verse('siempre supiste (que)'),
    new Verse('sos una mujer (aunque)'),
    new Verse('tengas cuerpo de hombre, o mejor (que)'),
    new Verse('"hombre" y "mujer" no son más (que)'),
    new Verse('rótulos, signos arbitrarios (que)'),
    new Verse('las personas usan (como)'),
    new Verse('herramientas para describir la realidad (que)'),
    new Verse('es más compleja y rica (que)'),
    new Verse('las palabras que se usan (para)'),
    new Verse('describirla, siempre insuficientes, (pero)'),
    new Verse('a veces los nombres (que)'),
    new Verse('le damos a las cosas tienen (una)'),
    new Verse('función performativa (porque)'),
    new Verse('representan un acuerdo entre personas (que)'),
    new Verse('usan palabras (como)'),
    new Verse('"dinero" y "papel higiénico" (que)'),
    new Verse('no son sino nombres para el papel (pero)'),
    new Verse('determinan el modo en (que)'),
    new Verse('los usaremos y por eso es violento (que)'),
    new Verse('no quieran llamarte "mujer" (aunque)'),
  ],
  '8': [
    new Verse('dime madre si es cierto — que estoy enamorada ()'),
    new Verse('reclino las cansadas manos sobre mi pecho ()'),
    new Verse('si habrá siempre vergüenzas debajo de mi falda ()'),
    new Verse('si me azota el estigma de todos los silencios ()'),
    new Verse('en qué espejos mi boca se verá reflejada ()'),
    new Verse('dime madre si es cierto que estoy embarazada ()'),
    new Verse('cómo cargaré a solas el peso de estos cuerpos ()'),
    new Verse('si en mi interior el feto puede oír mis palabras ()'),
    new Verse('cómo haré para darle todo lo que no tengo ()'),
    new Verse('si tengo solamente mis brazos y mis lágrimas ()'),
    new Verse('dime madre si hay forma de encontrar un consuelo ()'),
    new Verse('cómo afrontar el miedo de lo que tengo adentro ()'),
    new Verse('si veré mis entrañas mutiladas vacías ()'),
    new Verse('temiendo hasta la muerte que el bebé nazca muerto ()'),
    new Verse('o que al nacer despiertes en esta pesadilla ()'),
    new Verse('dime madre si siempre va a perseguirme el monstruo ()'),
    new Verse('del hombre masturbándose mientras me vigilaba ()'),
    new Verse('sin saber que mis manos son puñales filosos ()'),
    new Verse('que así como dan vida pueden arrebatarla ()'),
    new Verse('dime madre en qué ríos navegan sus despojos ()'),
  ],
  '9': [
    new Verse('mi abuela (que)'),
    new Verse('no pudo ser médica (porque)'),
    new Verse('solamente estudió su hermano (que)'),
    new Verse('trataba como esclava a su mujer (que)'),
    new Verse('baldeaba la vereda de rodillas (mientras)'),
    new Verse('él jugaba a la baraja (que)'),
    new Verse('reproducía las desigualdades (con)'),
    new Verse('cuatro reyes mandando (sobre)'),
    new Verse('cuatro reinas (que)'),
    new Verse('tenían que andar bien vestidas para (que)'),
    new Verse('siempre parezcan el trofeo (del)'),
    new Verse('héroe de la película (que)'),
    new Verse('ganó el premio al mejor guión pero (donde)'),
    new Verse('las mujeres son representaciones (que)'),
    new Verse('se sexualizan pero no intervienen más (que)'),
    new Verse('para decir estupideces (porque)'),
    new Verse('Dios y los profetas son hombres (y)'),
    new Verse('las escrituras prometen vírgenes para (quienes)'),
    new Verse('maten a los infieles (que)'),
    new Verse('no crean en su ley bajo la (que)'),
  ],
};

