
const REPO = [
  'La niña de telaraña\nun día se despertó\nsobre una cuna de asfalto\ny un plato de se acabó.\nLa niña de telaraña\nun día se fue a dormir,\nsoñó con un arcoíris\ny con flores de jazmín.\nLa niña de telaraña\nun día se despertó\nal desamparo del cielo\ny al abrigo del dolor.\nLa niña de telaraña\nun día se fue a dormir,\nsoñó todas las estrellas\ny los árboles de abril.\nLa niña de telaraña\nun día se despertó\nen una ciudad con hambre\ny un mundo sin corazón.\nDuerme pequeño bebé\nque tu madre ya está muerta.\nTus tiernos brazos nacidos\nno pudieron sostenerla.\nDuerme pequeño bebé\nque este cielo son tus sábanas.\nQue hoy no hay calor ni comida,\ny habrá hambre y frío mañana.\nDuerme pequeño bebé,\nque brilla la luna negra,\nque tu vida son los ríos\ny tu cuna las estrellas.\nLa niña de telaraña\nun día se fue a dormir\ny no quiso despertarse\npara dejar de vivir.\n',
  'Llénense las tinieblas de cáncer.\nAve que renaces de tus cenizas:\nllévame hacia el pasaje, la abadía y la espada.\nSi todo aquello que creí haber sido\nestá dejando de permanecer.\nAve que me conduces a la muerte:\nla envergadura de tu lomo emplumado\nes la mano de fierro que me aferra y me suelta.\nPlaneamos por los bordes fractales de la arena de la memoria.\nEl ojo de la mente va iluminando los complejos accidentes de un atlas.\nDescenso plácido sobre tus alas.\nVista panorámica que me ofrece.\nYa no hay características inherentes a mí.\nAcampo en la planicie sembrada de mi propia mandrágora.\nYa soy todas las conchas.\nVoy comprendiendo al fin que mis manos no me pertenecieron.\nLas memorias se despojan al final de sus máscaras.\nLos recuerdos desnudos se revelan como figuraciones ilusorias.\nLas formas y siluetas se desvanecen\ncomo al asir el éter en los sueños.\nEl pájaro me deposita en la noche y se va volando.\nQuedo en la soledad de la negrura\nderramando mis desconsuelos en lágrimas.\nYa ni siquiera queda ese agujero\nque suele aparecernos en las panzas.\nFinitud de los álguienes.\nEternidad de pájaros que eclipsan la multiplicidad del ocaso.\n',
  'Vuelvo a soñar tu nombre que me grita,\nvuelvo a escribir el eco de tus pasos,\ncon las últimas fuerzas de mis brazos\nriego el recuerdo de tu flor marchita.\nMe asomo a la negrura que me habita:\nsé que sólo me quedan tus pedazos,\nque el alba se convierte en el ocaso,\nque todo muere y nada resucita.\nEl sol iluminó tu entierro un día\ny hoy ilumina tu pared vacía.\nLa ausencia de tu flor entre la mierda,\nla esencia de tu piel en las almohadas,\ncada instante que pasa me recuerda\nque fuimos todo y no seremos nada.\n',
  'Todavía conservo en una vitrina\nel corazón que aquella tarde me prestaste\ncomo un secreto que resguardábamos\nde las inclemencias del tiempo y de los otros.\nSusurrabas entre las sombras de los lapachos\ntu anhelo como un mosaico ya reducido a añicos\nde acunar en tus brazos una criatura.\nDecías que los años eran relámpagos\nque fulguraban con la brevedad\nde la placenta desgarrada por la luna.\nTodavía conservo en una vitrina\nel corazón que aquella tarde me prestaste\ncomo las flores de manzanilla que desecabas en los misales,\ncomo una plegaria que murmuro devotamente\ncon la certeza de que no puede salvarme.',
  'Bajo su férrea luz, que rige el día\ny el cálculo del rumbo de las naves,\nel ejército persa alcanzó el grave\nesplendor que precede a la agonía.\nSu exacta, luminosa, tiranía\ndicta el canto y la calma de las aves,\ny en su reflejo circular se saben\ncifrar las fases de la hechicería.\nEl sol, que ha atestiguado la caída\nde los imperios, de sus vagos rastros,\ncomo un inmóvil y omnisciente ojo,\nha iluminado nuestras breves vidas.\nY algún día, las luces de los astros\nhabrán de iluminar nuestros despojos.\n',
  'No habrá uno solo entre los atributos\ninfinitos de Dios que permanezca,\nni habrá una sola rosa que florezca\nsin prometer su venidero fruto.\nEntre estos algorítmicos minutos\nno hay un segundo que nos pertenezca,\nni hay un retoño cuya sombra crezca\nsin evocar su inevitable luto.\nLa combustión del tiempo nos abrasa:\nnada perdura, todo es transitorio,\nun aspecto fortuito del presente.\nY el pensamiento de que todo pasa\ntampoco es algo más que un ilusorio\ny pasajero estado de la mente.\n',
  'Postrado ante la arcana signatura\nde un volumen del Liber execrable,\nfue al descifrar un símbolo innombrable\nque vislumbró la eterna conjetura.\nLa incontenible luz de la locura\nle reveló el secreto interminable\ndel tiempo, que comprende la incontable\nprocesión de las múltiples criaturas.\nY al desgarrar el velo de la mente\ncomprendió que la vida es ilusoria:\nque no hay instante fuera del presente\nni hay otra opción más que seguir despierto.\n¿O cuál será el fulgor de tu memoria\ndespués del día en el que te hayas muerto?\n',
  'Una vez más los párpados se entregan\nal designio arbitrario de las vagas\nhoras en que lo claro se rezaga\ny las constelaciones se despliegan.\nSueño tu larga efigie que me indaga,\nmi cuerpo turbulento que navega,\ntu abrazo que me turba y me sosiega,\nmi corazón sin rumbo que naufraga.\nLa ventana recorta la simétrica\nsilueta blanca de la blanca luna.\nBajo la calculada luz geométrica\nabro en vano los labios y te llamo:\nel eco de tu ausente voz me acuna\ny entiendo finalmente que te amo.\n',
  'Las llamas consumieron las hermosas\ncartas que me escribiste, y sus cenizas\nque frágilmente se volatilizan\nson el polvo de negras mariposas.\nMe convoca una antífona monstruosa:\nel ángel te ha arrancado. Y, sin tu risa,\nmis llantos en la noche me esclavizan\ny caigo como un cuerpo en una fosa.\nLa incesante, morosa, gota cae\npero al fin el océano desborda.\nUna vez más el día se termina:\nla tarde derrumbándose me trae\nla agitación amortiguada y sorda\ndel corazón que se convierte en ruina.\n',
  'Se han de borrar los rastros de alegría\ny se han de disipar las presurosas\ngotas de sal que ruedan lacrimosas\npor las tibias mejillas. Todavía\nmi pecho alberga la ilusión vacía\nde que perdure al menos una cosa,\npero no hay en la esencia de la rosa\nnada que permanezca. La poesía\ntransmuta este fugaz momento en versos:\ny aunque nuestros minutos son escasos\ny en cambio inagotable el universo,\nbrota en mi corazón el afán vano,\nante las parcas luces del ocaso,\nde tus ojos, de verte, de tus manos.\n',
  'Con las manos manchadas acorralé mi corazón rebelde.\nAsfixiado por acogotamiento latió mi corazón al cielo abierto.\nEl arcángel montado sobre el centauro trotó en la ensilladura de la luna\ncon su rayo bramante seccionando en pedazos a los hemisferios del cielo.\nAnuncio de los truenos como piedras rompiendo su violencia contra las almas:\ncabalgares maniáticos de corceles de fuego por el desierto.\nAl término del día, cuando amainó la fuerza de la tormenta,\nya los cielos clareantes y las playas en calma,\nse multiplicaron las larvas\ndescomponiendo un cuerpo agusanado.\nMoraban en mi madre las alas de murciélago.\nBajó la diosa negra vestida en terciopelo:\nlas flores venenosas bordadas en su manto\nhicieron permanentes quietudes de tu llanto.\nEn otro tiempo no estuvimos muertos.\nEn otro tiempo fuimos las estrellas:\nsostuvimos el cielo con las manos.\nAl fin mi corazón fosilizado rimó con el silencio.\n¿Hay lo más amarillo?\n¿Hay lo más luminoso que el reflejo temblando\ndel sol sobre las aguas de los cántaros\nadonde acuden a beber las polícromas, cúbicas, mariposas?',
];
