
let NAMES = [
  "Martín",
  "Alejandra",
  "Héctor",
  "Jorge",
  "Carla",
  "Z.",
  "Daiana",
  "Ezequiel",
  "Juli",
  "Nicolás",
  "L.",
  "Yohanna",
  "T.",
  "María",
  "Ignacio",
  "B.",
];

let VERSES = {
  "Ezequiel": [
    "película cuarto de libra con queso cómo se llama",
    "tiempos violentos película completa",
    "tiempos violentos película completa español latino",
    "tiempos violentos película completa español latino gratis",
    "",
    "búsquedas raras en google",
    "búsquedas graciosas en google",
    "búsquedas más frecuentes en google 2020",
    "cuál es la mejor alternativa a google",
    "",
    "cómo se escribe deconstruido o deconstruído",
    "cómo se escribe deconstruido real academia española",
    "deconstruido por qué va sin acento",
    "cómo se dice acento o tilde",
    "",
    "voy a tener suerte",
    "voy a tener suerte no es poesía",
    "quién escribió voy a tener suerte",
    "análisis voy a tener suerte"
  ],
  "Carla": [
    "no me viene",
    "no me viene hace 2 meses",
    "no me viene hace 2 meses y tomo pastillas",
    "no me viene hace 2 meses y tomo pastillas test negativo",
    "",
    "pies hinchados",
    "pies hinchados embarazo",
    "pies hinchados embarazo es normal",
    "cómo deshinchar pies hinchados embarazo",
    "",
    "recién nacido peso",
    "recién nacido bajo peso",
    "recién nacido bajo peso extremo",
    "recién nacido bajo peso extremo riesgos",
    "",
    "duelo perinatal",
    "tasa de mortalidad perinatal",
    "tasa de mortalidad perinatal argentina",
    "psicóloga duelo perinatal"
  ],
  "Z.": [
    "mujer gritándole a gato",
    "mujer gritándole a gato meme",
    "mujer gritándole a gato meme origen",
    "crear meme mujer gritándole a gato",
    "",
    "pepa es lo mismo que lsd",
    "pepa droga es adictiva",
    "pepa droga duración",
    "cuánto dura el efecto de 1/4 de pepa",
    "",
    "por qué soy yo",
    "por qué yo soy yo",
    "por qué yo soy yo y no soy otra persona",
    "por qué estoy acá y no estoy en otro momento",
    "",
    "cuando el cuerpo muere la mente sigue",
    "puede seguir la conciencia después de la muerte",
    "qué cambia en el instante en el que una persona muere",
    "por qué una persona viva se convierte en una persona muerta"
  ],
  "Daiana": [
    "dejar de sufrir",
    "dejar de sufrir por tu ex",
    "cómo dejar en el pasado a tu ex",
    "cómo dejar el pasado atrás psicología",
    "",
    "dlasfjas",
    "fjdsklj fdlaskjdfas",
    "adsfkjad fskljasdflkj asdflkjasdf",
    "dsflkjas dsafkljdas asdfkljdasf",
    "",
    "por qué me enojo tanto",
    "por qué me enojo todo el tiempo",
    "por qué me enojo todo el tiempo con mi mamá",
    "por qué me persigue la desgracia gif",
    "",
    "soñar con peces",
    "soñar con peces muertos",
    "soñar con peces muertos qué significa",
    "soñar con peces muertos"
  ],
  "Ignacio": [
    "pity álvarez preso",
    "pity álvarez fotos preso",
    "pity álvarez edad",
    "pity álvarez joven fotos 1992",
    "",
    "vacunas causan esterilidad",
    "vacunas causan daño cerebral",
    "vacunas causan autismo",
    "vacunas causan autismo the lancet",
    "",
    "preservativo roto",
    "preservativo roto en la base",
    "preservativo roto qué hacer",
    "preservativo previene hpv",
    "",
    "diario olé",
    "diario olé river plate",
    "diario olé river plate refuerzos",
    "diario olé river campeón libertadores"
  ],
  "Alejandra": [
    "cómo hacer velas",
    "cómo hacer velas aromáticas",
    "cómo hacer velas aromáticas paso a paso",
    "dónde comprar materiales para hacer velas aromáticas",
    "",
    "agua gusto raro",
    "agua gusto raro caba",
    "el agua tiene gusto raro",
    "el agua tiene gusto a aceite de oliva",
    "",
    "borges la cábala",
    "borges la cábala conferencia",
    "quién escribió el golem",
    "der golem gustav meyrink",
    "",
    "plaga hormigas",
    "plaga hormigas rojas chiquitas",
    "plaga hormigas rojas chiquitas vinagre",
    "por qué las hormigas se llevan a las muertas"
  ],
  "B.": [
    "mi marido se fue",
    "mi marido se fue con su ex",
    "mi marido se fue pero no se llevó sus cosas",
    "mi marido se fue asesoría legal",
    "",
    "dejar de fumar",
    "dejar de fumar en cuarentena",
    "dejar de fumar engorda",
    "por qué dejar de fumar produce gases",
    "",
    "ofertas navideñas",
    "regalos de navidad económicos",
    "cómo le digo a mi hija que papá noel no existe",
    "cómo le digo a mi hija que su papá nos dejó",
    "",
    "dejar de buscar",
    "dejar de buscar respuestas",
    "enfermedad de buscar todo en internet",
    "dejar de buscar respuestas en internet"
  ],
  "T.": [
    "c++ af\_inet",
    "c++ af\_inet sock\_stream",
    "c++ af\_inet sock\_stream bind listen",
    "c++ af\_inet sock\_stream bind listen localhost",
    "",
    "5001-7626",
    "5001-7626 teléfono",
    "5001-7626 teléfono llaman varias veces",
    "5001-7626 teléfono llaman varias veces y cortan",
    "",
    "ramon llull",
    "ramon llull ars magna",
    "ramon llull ars magna generalis et ultima",
    "qué hacer una tarde de lluvia",
    "",
    "split ergativity",
    "split ergativity in tagalog",
    "tagalog ng focus",
    "morphosyntactic alignment in austronesian languages"
  ],
  "Yohanna": [
    "tiananmen plaza",
    "tiananmen plaza masacre",
    "tiananmen plaza masacre 1989",
    "tiananmen plaza masacre 1989 qué pasó",
    "",
    "la condesa sangrienta",
    "la condesa sangrienta alejandra pizarnik",
    "la condesa sangrienta alejandra pizarnik y santiago caruso",
    "quevedo epitafio sangrienta luna",
    "",
    "marcha ni una menos",
    "marcha contra el gobierno",
    "marcha por el aborto legal",
    "aborto legal en el hospital letra",
    "",
    "beso negro",
    "beso negro tips",
    "estimulación ano hombre",
    "estimulación bucal del ano"
  ],
  "Martín": [
    "piazzolla adiós nonino",
    "piazzolla adiós nonino partitura",
    "piazzolla adiós nonino partitura piano",
    "piazzolla adiós nonino partitura piano pdf",
    "",
    "pintura para madera",
    "pintura para madera exterior",
    "pintura para madera exterior envíos",
    "pintura para madera exterior precio litro",
    "",
    "receta panqueques",
    "receta panqueques fácil",
    "receta panqueques fácil video",
    "cantidad de ingredientes panqueques para 30 personas",
    "",
    "factura metrogas vencida",
    "factura metrogas vencida dónde pagar",
    "factura metrogas vencida dónde pagar online",
    "truchar medidor de gas argentina"
  ],
  "Juli": [
    "cbc dibujo cátedra murgia",
    "cbc dibujo cátedra murgia modelos de examen",
    "perdonar una infidelidad",
    "perdonar una infidelidad si yo también fui infiel",
    "",
    "astrocitoma glioma diferencias",
    "glioma difuso",
    "glioma difuso grado 3",
    "glioma difuso grado 3 esperanza de vida",
    "",
    "causas tumor cerebral niños",
    "el celular puede causar cáncer",
    "las radiaciones del celular pueden causar cáncer",
    "consecuencias operación tumor cerebral",
    "",
    "iron maiden recital",
    "iron maiden argentina entradas ticketek",
    "iron maiden recital horario",
    "estadio josé amalfitani cómo llegar"
  ],
  "Jorge": [
    "rubia argentina",
    "rubia argentina tetona",
    "rubia argentina tetona le dan por el culo",
    "rubia argentina tetona le dan por el culo y grita sacámela",
    "",
    "cuándo es el día de la madre",
    "regalos para el día de la madre",
    "camperas deportivas para mujer",
    "camperas deportivas para mujer talles grandes",
    "",
    "borrar búsquedas",
    "borrar historial de búsquedas",
    "cómo borrar historial de búsquedas",
    "eliminar historial de búsquedas completo",
    "",
    "luna roja fotos",
    "luna roja es de mal augurio",
    "por qué la luna se ve roja",
    "por qué la luna se ve roja eclipse de sangre"
  ],
  "L.": [
    "ayuda hijo con discapacidad",
    "ayuda hijo con discapacidad a cargo",
    "ayuda hijo con discapacidad a cargo hacienda",
    "ayuda familia numerosa hijo con discapacidad",
    "",
    "moquillo en perros",
    "moquillo en perros síntomas",
    "cómo saber si un perro tiene moquillo",
    "moquillo en perros remedios caseros",
    "",
    "escuelas especiales",
    "escuela para niños con discapacidad",
    "escuela para niños con discapacidad motriz",
    "escuela inclusiva niños con discapacidad zona sur",
    "",
    "longchamps la plata",
    "longchamps la plata colectivo duración",
    "longchamps la plata tren horarios",
    "longchamps estación tren roca"
  ],
  "María": [
    "cuándo cobran los docentes",
    "cuándo cobro el aguinaldo",
    "cuándo cobro el aguinaldo docente",
    "docentes pueden comprar dólares",
    "",
    "juego de células que se comen a otras",
    "agar.io bitcoin",
    "agar.io bitcoin hack",
    "agar.io bitcoin hack apk",
    "",
    "alquiler dueño directo",
    "pizzería los campeones",
    "pizzería los campeones teléfono",
    "pizzería los campeones delivery",
    "",
    "aries y acuario",
    "aries y acuario compatibilidad",
    "aries y acuario en la cama",
    "aries y aries se atraen"
  ],
  "Nicolás": [
    "mi familia me critica por todo",
    "cómo hago para irme de mi casa",
    "tramitar ciudadanía italiana",
    "me quiero escapar de mi casa",
    "",
    "tiene sentido vivir",
    "tiene sentido la vida",
    "qué sentido tiene vivir",
    "el mito de sísifo qué significa",
    "",
    "para qué seguir viviendo",
    "cómo se puede dejar de sufrir",
    "terminar con el sufrimiento",
    "estoy cansado de vivir"
  ],
  "Héctor": [
    "clima en tandil",
    "clima en tandil para el domingo",
    "indumentaria pesca tandil",
    "cuántos km tiene el dique de tandil",
    "",
    "créditos banco ciudad",
    "banco ciudad créditos tasa",
    "banco ciudad créditos consorcios",
    "banco ciudad créditos consorcios requisitos otorgamiento",
    "",
    "torneo apertura 2010",
    "torneo apertura 2010 goles",
    "torneo apertura 2010 goles estudiantes",
    "apertura 2010 quién hizo el gol estudiantes san lorenzo",
    "",
    "farmacia de turno",
    "farmacia de turno hoy",
    "farmacia de turno hoy osperyh",
    "farmacia de turno hoy osperyh san justo"
  ]
};

