let PARTS = [
  ["0 Buenos Aires",
    [
    "buenos aires'en",
    "zhameante el sol saliendo,",
    "sus trentidós lenguas'kon,",
    "resplandece las dórikas de mármol",
    "del pórtiko imponente de derexo.",
    "",
    "ciudad ke fue esplendor del virreynato",
    "y erigida sekreto'en",
    "desarmadero de fititos'sobre",
    "las ruinas kástor y póluks'en komo",
    "zhace el reflejo pálido de antanio.",
    "",
    "la húmeda tierra'bajo",
    "la red del subte línea Z orgánika",
    "kreciendo la fuerza'kon",
    "de la kara selvátika",
    "del indio sol y lunas espaniolas.",
    "",
    "las imprentas publikan",
    "ejemplares de diarios 普通话[pǔtōnghuà]'en",
    "anunciando zhuvia de las luciérnagas",
    "ke la tierra enkandilan kitinosas",
    "y sekan su de sed hinxada lengua."
	  ]
  ],
  ["1 Satélite joviano",
    [
    "ionizada la atmósfera",
    "del inhóspito 屁股[pìgu] del universo",
    "cirkundan módulos deskribiend'órbitas",
    "delke bajan kosmonautas soviétikas",
    "bebiendo lexe de sagradas vakas.",
    "",
    "el férreo núkleo de la tierra'desde",
    "emergió akezha nave de amplias velas",
    "alkanzó la velocidad de eskape",
    "y nos transportó párseks",
    "tal remoto sistema estelar'hasta.",
    "",
    "miles de ojos robótikos",
    "y sus kontroladores algorítmikos",
    "sensando los potenciales de hidrógeno",
    "la nube de gas tóksiko'en se adentran,",
    "y transfieren fotos polinomios'kon.",
    "",
    "científikes celebran",
    "gran salto de la posthumanidad:",
    "superioridad téknika",
    "permitirá el disenio de armas nuevas",
    "y someter los pueblos ekstranjeros."
	  ]
  ],
  ["2 Suburbio de Tokio",
    [
    "asesinato krudo de las ninias",
    "la alfombra'sobre zhacen desmembradas",
    "son el depósito sus karas muertas",
    "ánforas de arcizha'en",
    "maskarones de popa de los barkos fantasma.",
    "",
    "dicen ke el loko suelto ",
    "se evaporó la noxe silencios'en",
    "y ke su monoambiente makabro",
    "donde akontecieron los hexos",
    "azhanó la policía científika.",
    "",
    "dicen ke vaga las kazhes'por",
    "ke fue saksofonista de músika karnátika",
    "ta takadimi taka",
    "y ese polirritmo'kon",
    "akuxizhó sus víktimas.",
    "",
    "pena'en su alma fantasmal no duerme,",
    "buskando redimirse de sus aktos,",
    "y buska igual ke vos y zho buskamos",
    "eso ke nadie habrá de enkontrar nunka:",
    "la kara atrás de nuestra propia máskara."
	  ]
  ],
  ["3 Av. General José de San Martín",
    [
    "los dados ke arrojó el universo",
    "designaron ke duerma a la intemperie",
    "mirando el paso de los transeúntes",
    "ke me eskivan viéndome de reojo",
    "se mira un perro destripado'komo.",
    "",
    "tanto'kada un kristiano",
    "me trae agua kaliente, ropa blanka,",
    "salvando tales okasiones'pero",
    "me nutren desperdicios, piel de pozho",
    "y káskaras de mandarinas agrias.",
    "",
    "guardo el rekuerdo tenue de otras épokas",
    "ke supe figurarme el porvenir'en",
    "no obstante las palizas ke me daban.",
    "no habrá tenido más alternativa",
    "madre ke abandonarme unas zanjas'en.",
    "",
    "mis penas son innumerables'aunke",
    "las noxes'en de incertidumbre y hambre,",
    "mi mano alberga magras alegrías:",
    "la certeza del sol ke entibia el alma",
    "y el resplandor ke el korazón permea."
	  ]
  ],
  ["4 Hazhazgo arkeológiko",
    [
    "murió la abuela.",
    "la kara kieta'kon la sepultaron,",
    "tantas otras abuelas muertas'entre.",
    "no sé si habré de reenkontrar su tumba",
    "tantos zhantos y flores blankas'entre.",
    "",
    "rekuerdo su arrugada voz, hablándome",
    "de atesorar el úniko presente,",
    "porke la kasa se nos viene abajo,",
    "su atención al servir el té kaliente",
    "y sus manos bordando los paniuelos.",
    "",
    "sé ke la realidad y ke el rekuerdo",
    "de los momentos malos y los buenos",
    "se konfunden una kosa sola'en:",
    "la realidad no es más ke las memorias,",
    "unas fulguraciones ke rebrotan.",
    "",
    "kasa de la abuela'en vi la lata",
    "las kartas'kon de nuestros bisabuelos.",
    "y el papel amarizho'desde hablaron",
    "antiguos kuzhos huesos",
    "moran las lápidas mohosas'bajo."
	  ]
  ],
  ["5 Afrodita de políkromo trono",
    [
    "azher sonié kontigo y el suenio'en",
    "me xupabas la konxa y los testíkulos,",
    "galopabas mí'en kabazho'komo,",
    "degeneradamente,",
    "ternura'kon y pausa'kon, violencia'kon.",
    "",
    "hoy ke te miro fijo",
    "eskondo atrás de los eskivos ojos",
    "la vergüenza y el goce de esa imagen,",
    "ke repaso, mantra repetitivo,",
    "deklinaciones del latín homériko.",
    "",
    "kanto, musa, la kólera funesta",
    "ke me desterró al inframundo",
    "una centuria de súkubos'donde",
    "me martizhan los pezones y el pene",
    "y me inzhektan sondas el ojete'en.",
    "",
    "sé ke alguna vez fui feliz",
    "y no supe disfrutar lo ke tuve",
    "las preokupaciones kotidianas'por",
    "de se hace tarde el kolektivo'para",
    "y tengo ke planxar las kamisas."
	  ]
  ],
  ["6 La lexuza (hyéroglyphe G17)",
    [
    "los estigmas de la kruz anksata'kon",
    "máskara funeraria del faraón",
    "sus vísceras vasijas kanópikas'en",
    "entretanto xakales kontrapesan",
    "la pluma de Ma'at y el korazón.",
    "",
    "las barkas enfilaron al horizonte",
    "y mil dígitos del sol las akogen.",
    "el alma-pájaro abandona el kuerpo,",
    "el obelisko de granito'desde",
    "el cenit'hacia.",
    "",
    "sacerdotes lezhendo pergaminos hierátikos",
    "entonan las estrofas del himno de los muertos,",
    "vibran las kuerdas tensas de la lira,",
    "evokando los símbolos",
    "del 莲花[liánhuā] azul y la korona bífida:",
    "",
    "un día no habrá nadie ke te rekuerde,",
    "nuestra lengua será ininteligible,",
    "alguien profanará los jeroglífikos",
    "y desenterrará de las arenas",
    "tu kara embalsamada hace milenios."
	  ]
  ],
  ["7 Esbozo del elefante blanko",
    [
    "la bokanada de humo zhenándoté el abdomen",
    "te devolvió memorias ekstraviadas.",
    "flotabas las alfombras persas'sobre,",
    "la ekstensión de tus brazos era el mundo",
    "y el entrecejo todas las estrezhas.",
    "",
    "la mente se enfrentó un jakarandá",
    "de estornudos de los estegosaurios.",
    "y arborescentes",
    "kulebras karakúlikas borraxas",
    "serpentearon kobras mi pexo abierto.",
    "",
    "un buen día me eskapé de mi pueblo.",
    "me enkuentro a solas el océano'en",
    "tratando de regresar a mi kasa.",
    "las olas ke me apresan",
    "sabrán si habré de naufragar.",
    "",
    "miré el agua ke tiembla",
    "y zha no vi otra kosa más ke el agua.",
    "y rindiéndome a su empuje implakable",
    "tomé la bokanada kizás última,",
    "bajé los brazos y acepté mi suerte."
	  ]
  ],
  ["8 Despertar",
    [
    "¿kuál es el límite de lo enunciable?",
    "¿de kuáles kosas no es posible hablar?",
    "¿ké hacer lo ke no puedo decirte'kon?",
    "¿tendré ke hacer silencio?",
    "¿kómo sobrezhevar la soledad?",
    "",
    "¿hay algo más ke este sinfín de imágenes?",
    "¿adónde está el final del universo?",
    "¿por ké es tan grande y somos tan pekenios?",
    "¿habrá empezado el tiempo?",
    "¿podré aguantar lo inmenso del vacío, nuestra insignifikancia?",
    "",
    "¿por ké me enkuentro estos dos ojos'tras?",
    "¿por ké no soy un ave o una tortuga negra?",
    "¿será mi identidad algo tangible?",
    "¿o la kontinuidad será ilusoria",
    "y habré de vivenciar todas las vidas?",
    "",
    "¿seré la kosa únika",
    "ke experimenta todos los ahoras?",
    "¿kómo aguantar el peso intolerable",
    "de ke percibiré kada instante",
    "y sufriré todos los sufrimientos?"
	  ]
  ],
  ["9 Blitzkrieg",
    [
    "la 战争[zhànzhēng]'antes kosexamos papas",
    "y un día se zhevaron a mi hermano.",
    "el cepizho dental de mi madre'kon",
    "lavamos menstruación de padre muerto",
    "los sembradíos de tortuga'kontra.",
    "",
    "ver cielos'sin muxos meses'durante",
    "vivíamos metides sótanos'en",
    "komiendo kasi siempre sopa líkida",
    "la ansiedad'kon de la próksima bomba",
    "y alaridos agónikos.",
    "",
    "un tomate ke se pudrió",
    "retrataba el dolor vivo del odio",
    "y anhelar ke se mueran los otros.",
    "los rezhes sus muzhidas sizhas'desde",
    "y un peón degozhando otro peón.",
    "",
    "nuestros hijos legarán el presente:",
    "la injusticia, el miedo y la destrukción.",
    "y ke enfrentar tales designios'antes",
    "será mejor abandonar el barko",
    "y rajarse el fatal tiro la jeta'en."
	  ]
  ]
]

