
let VERSES = [
  [
    'Re piola la presencia',
    'poderosa del Espíritu Santo;',
    'no lo puedo creer boludo.',
    'Frente al altar de mis ancestros',
    'escrache en aerosol carmín sanguíneo:',
    'trata de blancas.',
    'En la placita',
    'que está frente a la Iglesia',
    'San Martín inmortalizado en bronce',
    'mira hacia el Cristo de madera.',
    'Al costado un fulano sin nombre ni apellido',
    'destinado a ser siempre el telón de fondo,',
    'nunca el protagonista,',
    'revuelve con un palo de madera',
    'en la ollita de cobre',
    'caramelizando garrapiñadas.',
    'Los turbina que rondan la parada del bondi',
    'tras la fila de esclavos asalariados',
    'balbuciendo la oración a la Virgen',
    'y sudando el pan nuestro de cada día:',
    '"Feliz me hace". "Saber que Dios". "Está conmigo".',
    'Y yéndome a la verga',
    'convoco tus arcanos,',
    'el arte oculto de la hechicería,',
    'el muñeco macabro del embrión muerto',
    'y te ofrendo el cadáver de una gallina negra.',
  ],
  [
    'Vieras amigo cómo el enano pedaleaba kilómetros,',
    'el guacho siempre iba punteando',
    'no obstante la brevedad de sus fémures ',
    'a la vanguardia de los peregrinos',
    'yendo a comprar un kilo de flautitas',
    'sobre la fucking bicicleta',
    'que tenía tatuada en el omóplato.',
    'Qué espectáculo que era verlo al enano carajo.',
    'Se la pasaba en la terminal ferroviaria',
    'levantando los puchos pisoteados de zapatillas,',
    'colorados de pintalabios origen China,',
    'para exprimir las últimas pitadas',
    'y el hollín ascendía en espirales',
    'como almas espectrales vagando en penitencia.',
    'Nos miraba y se le paraba el pito',
    'y alguna vez me hizo pis en la puerta.',
    'Pero un día la señora del diablo',
    'compró veneno precaución raticida',
    'y se lo mezcló bien mezclado.',
    'Qué pedazo de infeliz que era la vieja esa.',
    'El ruido líquido que hacía el enano quebrando',
    'de tallarines vomitados como a baldazos,',
    'bilis y fricativas guturales',
    'me salpicó corrosivo el pulóver',
    'con el olor pungente de la leche cortada.',
  ],
  [
    'En la vereda de los rascacielos',
    'bajo el naranja pálido',
    'de los albores de la madrugada ',
    'tratando de refugiarse de los peatones',
    'los dos adolescentes se succionan los cuellos,',
    'chupan mordiéndose las bocas.',
    'Por el elástico del calzoncillo',
    'y por la puntilla de la bombacha',
    'se descubren los pubis con los dedos,',
    'se empapan en el flujo tornasolado',
    'como la baba de los caracoles',
    'y el viscoso pegamento del semen.',
    'Acto con que la realidad fue clausurada: ',
    'las cortinas metálicas ya están bajas,',
    'los negocios ya cambiaron de dueño,',
    'los vidrios ya están rotos.',
    'Mis dos hijos descalzos con los buzos raídos,',
    'con las caras manchadas y los mocos sangrientos,',
    'como los barcos de papel de diario',
    'endebles ante la furia del vendaval,',
    'abandonados a la buena de Dios,',
    'reparten estampitas ajadas de los santos.',
    'Y un negro senegalés tomando mate',
    'con su túnica vívida de pigmentos florales',
    'despliega las baratijas de plástico.',
  ],
  [
    '¿Viste la negra?',
    'No te acordás la vieja que andaba por las plazas',
    'juntando los mendrugos de las palomas',
    'y cuando la mirábamos',
    'el corazón pinchaba como espinas,',
    'se nos venía abajo,',
    'y que un día agarró a los gritos pelados',
    'al veintidós llorando su angelito.',
    'La negra que la violó un director de escuela',
    'no le venía el ciclo por la anorexia.',
    'Pero contra el pronóstico',
    'de reclamarle huevos a una gallina muerta:',
    'la negra fue mamá.',
    'Cuando pariendo se abrió en dos la concha',
    'en flor y en abanico',
    'miles de rumbos iban desplegándose,',
    'la negra era el reflejo del universo,',
    'la negra era luz misma, y era belleza misma,',
    'y era el agua, y el viento.',
    'La recién nacha, ',
    'qué cosa rompehuevos por favor que era,',
    'lloraba que no te das una idea.',
    'Y en ese mantra yógico del llanto',
    'la serpiente enroscada trepó hasta el entrecejo',
    'y al fin murió la negra.',
    'Negra ya son diez años que te fuiste',
    'pero tu cara reaparece nítida ante la mía',
    'cuando boca arriba en la noche',
    'conjuro entre la niebla de los sueños',
    'tus labios que parece que aún respiran,',
    'la ternura de tus ojos de vidrio.',
  ],
  [
    '¿Te creés importante',
    'por el valor ficticio del convencional símbolo,',
    'por la ilusión de que los nombres',
    'con los que bautizamos a las cosas',
    'modifican la esencia de las cosas?',
    'Con la cabeza en alto desdeñosa',
    'nos mirás con la jeta de escupir el reflujo,',
    'nos basureás como a la servidumbre.',
    'Por eso me refriego, sabés,',
    'los huevos putrefactos con el agua bendita,',
    'me paso por el culo tus billetes de a mil.',
    'Tus nobiliarios títulos y el linaje patricio',
    'no habrán de libertarte',
    'de la peste, la senectud, la tumba,',
    'de que, como un cerámico, se quiebre',
    'tu ilusión de que algo te pertenece.',
    'Afuera de tu termotanque hace frío,',
    'ta jodida la calle,',
    'la gente va, ampollada, de sol a sol',
    'rompiéndose la espalda y en busca de laburo.',
    'La vida es un ritual enmarañado:',
    'quise asfixiar mis sentimientos',
    'y encadené mi amor en una cárcel,',
    'pero como un cachorro soñoliento',
    'se quiso despertar entre tus manos',
    'y ladraba labrando en la memoria',
    'tu perla misteriosa,',
    'la blanca hechicería de tus muslos.',
  ],
  [
    'Calamar de la noche,',
    'despiadada marítima criatura',
    'que sumerge nuestras embarcaciones,',
    'señor de los naufragios',
    'y de enormes ojos desorbitados:',
    'invoco tu presencia con temblor en los labios.',
    'En mi boca vive sólo tu nombre,',
    'tu cara puebla todos mis horrores,',
    'tu olor es el perfume del palosanto.',
    'Tus prénsiles tentáculos',
    'amenazan la vaga luz del alba.',
    'Tu fosa ha sido abierta,',
    'las lágrimas que plañes han salado los mares,',
    'tu oscuridad relumbra',
    'fosforescente en las profundidades',
    'con la luminiscencia de los ángeles',
    'entonando cánticos ancestrales.',
    'Calamar de la noche:',
    'las laboriosas civilizaciones',
    'resecas ya por el natrón del tiempo',
    'veneraron tu náutica presencia',
    'en ánforas e intrincados mosaicos.',
    'Calamar de la noche,',
    'señor de los naufragios,',
    'bajándote la luna',
    'encomiendo mi navío a tus manos:',
    'traigas la noche al día,',
    'ensombrezcas nuestros diarios caminos,',
    'nos protejan de los vientos tus brazos,',
    'los miedos borre el aura de tu llanto.',
  ],
  [
    'Constará que a las diez de la mañana',
    'personal de limpieza de la hostería',
    'nos golpeará la puerta,',
    'primero suavemente, y a los gritos después,',
    'y para cuando ingresen a la 114',
    'estaremos ya muertas en las camas.',
    'Dos no identificadas de sexo femenino,',
    'ambos cuerpos desnudos',
    'en posición decúbito dorsal;',
    'causa de muerte: herida',
    'de proyectil de arma de fuego.',
    'Las memorias lactantes',
    'de succionar las tetas de mamá,',
    'rasparnos las rodillas jugando a la escondida,',
    'aplastar caracoles en un frasco,',
    'se tornarán violáceas',
    'y las deglutirán las larvas de mosca.',
    'En las medias de algodón y poliéster',
    'se irán descomponiendo los pies con los que andábamos.',
    'En las panzas contendremos comida',
    'destinada a no salir por los anos.',
    'Ni malabareando limones',
    'magullados de tanto manoseo,',
    'ni cuidando los autos con franelas naranjas,',
    'ni enjabonando parabrisas',
    'ganaremos el pan en los semáforos.',
    'Sé que terminaremos',
    'como restos de pollo que dejó el perro',
    'en una bolsa de basura negra,',
    'como frascos vacíos sin clavos oxidados.',
    '¿Qué significado tendrán los días',
    'en que nos reíamos y sufríamos',
    'cuando vuelvan nuestros cuerpos al barro?',
  ],
  [
    'Mi madre no me habla.',
    'La miro suplicando pero sigue callada.',
    'Me arrodillo y ruego por sus palabras',
    'pero permanece como una estatua.',
    'Su hermetismo es un cuchillo en la panza,',
    'una puñalada que me desgarra',
    'y sin el sol se me marchita el alma.',
    'Mamá, me estoy secando como una planta,',
    'los segundos que pasan',
    'tachan las letras de mi nombre,',
    'me trituran el esqueleto en ruinas',
    'y me caigo a pedazos,',
    'me cruzan las costillas como una lanza.',
    'Mamá, perdón por el abandonarte,',
    'el desprecio, el descuido y la indiferencia,',
    'perdón por haber roto tu corazón,',
    'por ser retrato de tus decepciones,',
    'tu cruz y tu cadalso,',
    'este fruto monstruoso de tu vientre,',
    'esta nube que oscurece tu cielo,',
    'este animal indigno del calor de tu abrazo.',
    'Aunque pasen los años y se extienda el silencio',
    'abrumado de dudas y de arrepentimiento',
    'te seguiré queriendo.',
  ],
  [
    'Cuando cierres los párpados y de vuelta los abras',
    'y en otro plano al ente subterráneo te enfrente',
    'la bóveda de cráneos de sol resplandeciente,',
    'y en tu faringe hueca no sobren más palabras,',
    'cuando las escaleras que hirviente sangre labra',
    'desciendas, y contemples los afluentes ríos,',
    'y el cuerpo que ocupabas se perciba vacío',
    'y no quede otra cosa que estas pocas palabras:',
    'sabrás que tu existencia fue un volátil murmullo,',
    'una visión efímera de una mancha borrosa,',
    'sabrás que no hubo nada verdadero ni tuyo',
    'en todas las verdades a las que te aferrabas,',
    'y sabrás nuevamente que sos aquella cosa',
    'que no empieza ni muere, ni nace, ni se acaba.',
  ],
  [
    'De niños me miraste dulcemente',
    'y nos enamoramos: nos temblaban los músculos,',
    'los ojos se nos volvían remansos',
    'y no nos aguantábamos las ganas de abrazarnos como locos.',
    'Pero la vida nos lanzó a piedrazos',
    'y hacía veinte años que ya no nos veíamos las caras.',
    'Pasábamos los días mirando compulsivamente pantallas,',
    'mensajes codificados con luces que nos quitaban el sueño,',
    'descripciones simbólicas del estado exacto del universo,',
    'de calles empedradas con el rompecabezas de adoquines',
    'y el mito urbano de la higuera en flor.',
    'Y pese a que seguíamos creyendo',
    'en ese mundo al que nos referíamos,',
    'ya nunca transitábamos las largas avenidas,',
    'los árboles frutales quizás estaban secos.',
    'La realidad se había convertido',
    'en una hipótesis innecesaria.',
    'Navegábamos días de representaciones',
    'que eran la verdadera y única realidad.',
    'Y mirando los símbolos',
    'que ya no significan más que símbolos',
    'que ya no significan más que símbolos',
    'me la paso esperando respuestas que no llegan:',
    'que alguien prescindirá de mis servicios',
    'y engañaré el estómago con unos mates tibios,',
    'que hoy es tu velatorio y el entierro es mañana',
    'y en todos estos años',
    'no me animé a decirte que te amaba.',
    'La poesía genuina no está ni en las pantallas ni en los libros,',
    'ni en las recitaciones de poesía:',
    'es el "Raquel te amo"',
    'rayado con la birome sin tinta',
    'en la puerta del inodoro público.',
  ]
];

